web:
  build: .
  command: bundle exec lotus server --host='0.0.0.0' --port=2300
  volumes:
    - .:/lotus_sample
  ports:
    - "2300:2300"
  volumes_from:
    - bundle
bundle:
  image: lotussample_web
  volumes:
    - /bundle
